### ISSUE TITLE
Ulster county partially dropped in 2022 statewide file?

### ISSUE THREAD

**Issue by sbaltzmit** [openelections/openelections-data-ny#143]
The 2022 statewide file is superbly accurate New York precinct data. I just wanted to raise an extremely minor issue that I think is very easy to fix: is it possible that the Ulster county file get somehow truncated during the merge into the statewide file? 

Here's why I ask.

In adding up votes for all the candidates in the main statewide file (https://github.com/openelections/openelections-data-ny/blob/master/2022/20221108__ny__general__precinct.csv), I found that in U.S. House district 18 the vote totals for the candidates (Pat Ryan and Colin J Schmitt) are about 20% too small.

I checked the counties in which they have vote totals, and it's just `Dutchess` and `Orange`. But that district includes Ulster county too.

The very good news though is that I do see those votes in the original Ulster county source file (https://github.com/openelections/openelections-data-ny/issues/127#issuecomment-1486015305).

If I add the candidates' vote totals from the Ulster county vote total to their votes in the statewide file, I get much much closer to the right vote totals.

So I think the U.S. House rows may have somehow been dropped when the Ulster county file was merged in.

**Comment by dwillis** [comment]
@sbaltzmit thanks - needed to fix the office titles for Senate and House in Ulster, and we've regenerated the statewide file.
