### ISSUE TITLE
Error in 2016 Suffolk general results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-ny#30]
Reported by John Johnson of Marquette: The file contains the same vote total for Clinton in multiple party lines. Specifically, Clinton's vote in "DEM" lines is identical to her vote in "WEP" (Women's Equality Party) lines. Somewhere the two must have been conflated.

**Comment by lephead** [comment]
Here is my 2016 Suffolk New York.  It has totals for each party and candidate.  Somebody must not have been paying close attention when they changed my chart to fit their format.

[2016 SUFFOLK NY.xlsx](https://github.com/openelections/openelections-data-ny/files/1082791/2016.SUFFOLK.NY.xlsx)

**Comment by dwillis** [comment]
This is fixed now.
