### ISSUE TITLE
2016 General County WOR & WEP parties?

### ISSUE THREAD

**Issue by hodgesmr** [openelections/openelections-data-ny#34]
I noticed that in [20161108__ny__general.csv](https://github.com/openelections/openelections-data-ny/blob/master/2016/20161108__ny__general.csv) Hillary Clinton has multiple vote tallies for the same county under the parties: `DEM`, `WOR`, and `WEP`. Is this an artifact of some strange reporting that NY does, or was something parsed incorrectly?

Example:

```
Kings, President, DEM, Hillary Clinton, 611439
Kings, President, WOR, Hillary Clinton, 26578
Kings, President, WEP, Hillary Clinton, 2536
```

**Comment by dwillis** [comment]
@hodgesmr it is an artifact; NY permits candidates to run on multiple party lines and reports their totals for each party. Most results apps/maps roll them up into a single total. WOR is the Working Families Party and WEP is the Women's Equality Party.

**Comment by hodgesmr** [comment]
Today I learned!
