### ISSUE TITLE
Layout of 2016 precinct returns from St. Lawrence County

### ISSUE THREAD

**Issue by jamesdunham** [openelections/openelections-data-ny#48]
Should this be changed? The [2016 precinct returns from St. Lawrence County](https://github.com/openelections/openelections-data-ny/blob/master/2016/20161108__ny__general__st_lawrence__precinct.csv) don't include a `votes` column. They instead take a wide format where vote mode subtotals are in columns:
```
         county  precinct office district party    candidate total machine_votes absentee absentee_hc affidavit
1: St. Lawrence Brasher 1              NA       Ballots Cast   374           353       17          NA         4
2: St. Lawrence Brasher 2              NA       Ballots Cast   519           479       28          NA        12
3: St. Lawrence  Canton 1              NA       Ballots Cast   654           570       70          NA        14
```

To make the layout predictable without discarding the mode information, (1) `total` could be renamed `votes` and the mode columns left wide, or (2) the table could be melted and a `mode` column added, like this:

```
         county  precinct office district party    candidate  mode votes
1: St. Lawrence Brasher 1              NA       Ballots Cast total   374
2: St. Lawrence Brasher 2              NA       Ballots Cast total   519
3: St. Lawrence  Canton 1              NA       Ballots Cast total   654
```

In which case the rows where `mode == total` could be kept or dropped. What are thoughts? I'm not sure how to apply the [results spec](https://github.com/openelections/specs/wiki/Results-Data-Spec-Version-2).

**Comment by dwillis** [comment]
Yes, the `total` column should be renamed to `votes`, leaving the others in place.
