### ISSUE TITLE
Is the file name "20161108__ny__general.csv" correct?

### ISSUE THREAD

**Issue by jeremiak** [openelections/openelections-data-ny#64]
Wondering if "20161108__ny__general.csv" should be "20161108__ny__general__county.csv" instead?

It seems like the same file for [Texas](https://raw.githubusercontent.com/openelections/openelections-data-tx/master/2016/20161108__tx__general__county.csv) and for [Tennessee](https://github.com/openelections/openelections-data-tn/blob/master/2016/20161108__tn__general__county.csv) have the `__county` appended to the name before the file extension. I didn't find anything about file naming in the documentation but I could've missed it.

**Comment by sonyabea** [comment]
yup, these look like county-level results. You fork, change the name and submit a pull request :)

**Comment by dwillis** [comment]
@jeremiak @sonyabea We've been inconsistent on this, but county-level results files should include the `__county` segment in the name, yes.

**Comment by jeremiak** [comment]
Great, I'll open a PR then :)
