### ISSUE TITLE
US House Races missing in statewide precinct results file

### ISSUE THREAD

**Issue by dbroockman** [openelections/openelections-data-ny#71]
US House races appear to be missing in https://github.com/openelections/openelections-data-ny/blob/master/2018/20181106__ny__general__precinct.csv for the following counties:

- [x] Broome
- [x] Cayuga
- [x] Clinton
- [x] Cortland
- [x] Dutchess
- [x] Kings
- [x] Oneida
- [x] Otsego
- [x] Richmond
- [x] Sullivan

It is possible other countries or other races may be missing as well, these are the only ones I was using.

**Comment by dwillis** [comment]
@dbroockman Thanks - we've replaced the statewide precinct file to add House races (and some others that did not have standardized office names) to it.
