### ISSUE TITLE
Corrupt file for Suffolk general precinct level

### ISSUE THREAD

**Issue by oscarbatori** [openelections/openelections-data-ny#75]
https://raw.githubusercontent.com/openelections/openelections-data-ny/master/2012/counties/20121106__ny__general__suffolk__precinct.csv

Line has an extra comma, breaking CSV parsing 75924.

**Comment by dwillis** [comment]
@oscarbatori hey, thanks for this. I can't replicate the error - have tried parsing it with Ruby and Python's csv modules and both worked.

**Comment by oscarbatori** [comment]
Strange, I cannot parse this file... I will dig in a bit and see if something completely weird happened...

**Comment by carbonphyber** [comment]
It looks like there is an extra column added in some rows (see screenshot after "State Senate" column).
<img width="796" alt="Screen Shot 2021-04-06 at 03 16 16" src="https://user-images.githubusercontent.com/363098/113696123-7523da00-9686-11eb-8f84-5d66a25d03ac.png">

**Comment by carbonphyber** [comment]
Also, I noticed there are a lot of these State Senate office rows where the same {precinct, office, district, candidate} tuple has multiple rows with different {party, votes}. Is this expected? Is it a feature of NY ballots/voting?

**Comment by dwillis** [comment]
@carbonphyber Yes, in NY candidates can run on multiple party lines.
