### ISSUE TITLE
2012 votes column contain erroneous values

### ISSUE THREAD

**Issue by oscarbatori** [openelections/openelections-data-ny#76]
`2012/20121106__ny__general__precinct.csv` and `2014/20141104__ny__general__precinct.csv` both contain a bunch of strings in the votes column (containing mostly candidate names).

**Comment by carbonphyber** [comment]
Likely fixed by PR #88 . Will try and verify later.

**Comment by carbonphyber** [comment]
Verified fixed. There are no candidate names in the "votes" column anymore.
