### ISSUE TITLE
2020 General Data - Suffolk County Issue Discovered

### ISSUE THREAD

**Issue by arapf** [openelections/openelections-data-ny#91]
Hello! Looks like the precinct-level 2020 numbers are off in Suffolk by precinct/town in the race for president. 

For the presidential race, the candidates have numbers for each of Smithtown's 92 precincts, then there's a repeated entry for precincts 1-42. That second entry is *actually* Southampton 1-42, the results of which are missing at the presidential level.

Haven't looked at state races, but that's the only federal race affected - U.S. House is fine. Just thought I'd flag to hopefully save someone the trouble.

**Comment by warwickmm** [comment]
Here's a direct link to the problematic file

https://github.com/openelections/openelections-data-ny/blob/9e3b7f1c0e4af6e8f0aae416b9d40f3e12b2c5eb/2020/counties/20201103__ny__general__suffolk__precinct.csv
